name: Check Detran Meier

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule: # execute every 2 hours
    - cron: "* */1 * * *"
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:      
      # Checkout
      - name: Check out repository code
        uses: actions/checkout@v1

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
        
      - name: Run script
        env:
          GMAIL_USER: uilton.dev@gmail.com
          GMAIL_PASS: ${{ secrets.GITHUB_PASS }}
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          pipenv run python main.py
